In [1]:
import numpy as np

In [43]:
np.__version__

'2.2.6'

In [6]:
li1 = [1, 2.0, '3']
li1

[1, 2.0, '3']

In [7]:
ar1 = np.array(object = li1)
ar1

array(['1', '2.0', '3'], dtype='<U32')

In [8]:
type(ar1)

numpy.ndarray

In [9]:
ar1.ndim

1

In [10]:
ar1.shape

(3,)

In [11]:
ar1.size

3

In [12]:
ar1.dtype

dtype('<U32')

In [13]:
ar1

array(['1', '2.0', '3'], dtype='<U32')

In [14]:
ar1.astype(int)

ValueError: invalid literal for int() with base 10: np.str_('2.0')

In [15]:
ar1.astype(float)

array([1., 2., 3.])

In [16]:
# method chaining
ar1.astype(float).astype(int)

array([1, 2, 3])

In [17]:
ar1.astype(float).astype(int).astype(str)

array(['1', '2', '3'], dtype='<U21')

In [19]:
li1

[1, 2.0, '3']

In [18]:
np.array(object = li1, dtype = int)

array([1, 2, 3])

In [20]:
np.array(object = li1, dtype = float)

array([1., 2., 3.])

In [21]:
np.array(object = li1, dtype = str)

array(['1', '2.0', '3'], dtype='<U3')

In [22]:
np.array(object = li1, dtype = object)

array([1, 2.0, '3'], dtype=object)

In [23]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [24]:
list(range(1, 6))

[1, 2, 3, 4, 5]

In [25]:
list(range(1, 6, 2))

[1, 3, 5]

In [26]:
list(range(0, 1, 0.1))

TypeError: 'float' object cannot be interpreted as an integer

In [28]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [29]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [30]:
np.arange(1, 6, 2)

array([1, 3, 5])

In [31]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [32]:
np.arange(0, 1.1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [34]:
np.linspace(0, 1, 10+1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [35]:
np.linspace(80, 75, 30+1)

array([80.        , 79.83333333, 79.66666667, 79.5       , 79.33333333,
       79.16666667, 79.        , 78.83333333, 78.66666667, 78.5       ,
       78.33333333, 78.16666667, 78.        , 77.83333333, 77.66666667,
       77.5       , 77.33333333, 77.16666667, 77.        , 76.83333333,
       76.66666667, 76.5       , 76.33333333, 76.16666667, 76.        ,
       75.83333333, 75.66666667, 75.5       , 75.33333333, 75.16666667,
       75.        ])

In [36]:
np.tile(ar1, 2)

array(['1', '2.0', '3', '1', '2.0', '3'], dtype='<U32')

In [37]:
np.repeat(ar1, 2)

array(['1', '1', '2.0', '2.0', '3', '3'], dtype='<U32')

In [38]:
np.repeat(ar1, [3, 2, 1])

array(['1', '1', '1', '2.0', '2.0', '3'], dtype='<U32')

In [39]:
ar1 = np.arange(1, 12, 2)
ar1

array([ 1,  3,  5,  7,  9, 11])

In [40]:
ar1[0]

np.int64(1)

In [41]:
ar1[1]

np.int64(3)

In [42]:
ar1[-1]

np.int64(11)

In [44]:
ar1[-1].item()

11

In [45]:
ar1[0:3]

array([1, 3, 5])

In [46]:
ar1[:3]

array([1, 3, 5])

In [47]:
ar1[3:]

array([ 7,  9, 11])

In [48]:
ar1[:]

array([ 1,  3,  5,  7,  9, 11])

In [49]:
ar1[[3, 1, 2]]

array([7, 3, 5])

In [50]:
ar1[[3, 3, 3]]

array([7, 7, 7])

In [51]:
ar1[[False, False, False, True, True, True]]

array([ 7,  9, 11])

In [52]:
ar1[ar1 >= 7]

array([ 7,  9, 11])

In [53]:
ar1[[3]*3]

array([7, 7, 7])

In [54]:
ar1[np.tile(3, 3)]

array([7, 7, 7])

In [55]:
ar1[[False]*3 + [True]*3]

array([ 7,  9, 11])

In [56]:
ar1[np.repeat([False, True], 3)]

array([ 7,  9, 11])

In [57]:
li2 = [[1, 2, 3], [4, 5, 6]]
li2

[[1, 2, 3], [4, 5, 6]]

In [58]:
ar2 = np.array(object = li2)
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
type(ar2)

numpy.ndarray

In [60]:
ar2.ndim

2

In [61]:
ar2.shape

(2, 3)

In [62]:
ar2.size

6

In [63]:
ar2.dtype

dtype('int64')

In [64]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
ar2[0, 0]

np.int64(1)

In [66]:
ar2[0]

array([1, 2, 3])

In [67]:
ar2[0, :]

array([1, 2, 3])

In [68]:
ar2[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [69]:
ar2[:, 1:3]

array([[2, 3],
       [5, 6]])

In [70]:
ar2[:, [2, 1]]

array([[3, 2],
       [6, 5]])

In [71]:
ar1

array([ 1,  3,  5,  7,  9, 11])

In [72]:
ar1.reshape(2, 3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [73]:
ar1.reshape(2, 3, order = 'F')

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [74]:
ar2 = ar1.reshape(2, -1)
ar2

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [75]:
ar2.flatten()

array([ 1,  3,  5,  7,  9, 11])

In [76]:
ar2.ravel()

array([ 1,  3,  5,  7,  9, 11])

In [80]:
ar1 = np.array([[1, 2, 3]])
ar1 + 1

array([[2, 3, 4]])

In [82]:
ar2 = ar1.reshape(-1, 1)
ar2 * 2

array([[2],
       [4],
       [6]])

In [83]:
ar1 = np.array([i**2 for i in range(1, 6)])
ar1

array([ 1,  4,  9, 16, 25])

In [85]:
np.diff(ar1, n=2)

array([2, 2, 2])

In [91]:
ar1 = np.array(object = [1, 5, 0, 3, 7, 8, 3, 5, 0, 8])

In [87]:
np.min(ar1)

np.int64(0)

In [88]:
np.max(ar1)

np.int64(8)

In [92]:
np.argmin(ar1)

np.int64(2)

In [93]:
np.argmax(ar1)

np.int64(5)

In [94]:
np.argsort(ar1)

array([2, 8, 0, 3, 6, 1, 7, 4, 5, 9])

In [97]:
ar1.tolist().count(np.min(ar1))

2

In [100]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [101]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [102]:
for i in range(5):
    print(np.random.rand())

0.7203244934421581
0.00011437481734488664
0.30233257263183977
0.14675589081711304
0.0923385947687978


In [103]:
for i in range(5):
    np.random.seed(1)
    print(np.random.rand())

0.417022004702574
0.417022004702574
0.417022004702574
0.417022004702574
0.417022004702574


In [104]:
np.random.seed(1)
for i in range(5):
    print(np.random.rand())

0.417022004702574
0.7203244934421581
0.00011437481734488664
0.30233257263183977
0.14675589081711304


In [105]:
np.random.seed(1)
for i in range(5):
    print(np.random.rand())

0.417022004702574
0.7203244934421581
0.00011437481734488664
0.30233257263183977
0.14675589081711304


In [108]:
np.random.randint(5)

4

In [111]:
np.random.randint(1, 7, 5)

array([6, 3, 5, 2, 2], dtype=int32)

In [116]:
dice = np.random.randint(1, 7, 100000)

In [117]:
for i in range(1, 7):
    print(dice.tolist().count(i))

16720
16647
16722
16553
16697
16661


In [122]:
for i in range(10):
    lotto = np.random.choice(a = range(1, 46), size = 6, replace = False)
    print(sorted(lotto.tolist()))

[1, 6, 10, 11, 44, 45]
[3, 4, 16, 20, 21, 27]
[11, 12, 17, 25, 27, 36]
[1, 2, 7, 11, 29, 32]
[9, 13, 25, 27, 33, 36]
[10, 13, 16, 20, 29, 30]
[5, 23, 24, 32, 40, 45]
[4, 7, 20, 28, 31, 45]
[5, 7, 11, 22, 35, 42]
[9, 10, 17, 24, 43, 45]


In [123]:
import pandas as pd

In [124]:
li1

[1, 2.0, '3']

In [125]:
np.array(object = li1)

array(['1', '2.0', '3'], dtype='<U32')

In [126]:
sr = pd.Series(data = li1)
sr

0      1
1    2.0
2      3
dtype: object

In [127]:
type(sr)

pandas.core.series.Series

In [128]:
for i in sr:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>


In [129]:
sr + 1

TypeError: can only concatenate str (not "int") to str

In [130]:
sr + '1'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [131]:
sr

0      1
1    2.0
2      3
dtype: object

In [133]:
sr.astype(str) + '1'

0      11
1    2.01
2      31
dtype: object

In [135]:
sr.astype(int) + 1

0    2
1    3
2    4
dtype: int64

In [136]:
sr.astype(float) + 1

0    2.0
1    3.0
2    4.0
dtype: float64

In [137]:
sr = sr.astype(float)

In [138]:
sr.shape

(3,)

In [139]:
sr.size

3

In [140]:
sr.dtype

dtype('float64')

In [141]:
sr.index

RangeIndex(start=0, stop=3, step=1)

In [142]:
sr.values

array([1., 2., 3.])

In [143]:
sr

0    1.0
1    2.0
2    3.0
dtype: float64

In [144]:
sr.index = [1, 2, 3]
sr

1    1.0
2    2.0
3    3.0
dtype: float64

In [145]:
sr.index = [1, 1, 1]
sr

1    1.0
1    2.0
1    3.0
dtype: float64

In [146]:
sr.index = [1.0, 2.0, 3.0]
sr

1.0    1.0
2.0    2.0
3.0    3.0
dtype: float64

In [147]:
sr.index = ['a', 'b', 'c']
sr

a    1.0
b    2.0
c    3.0
dtype: float64

In [148]:
pd.Series(data = li1, index = ['a', 'b', 'c'])

a      1
b    2.0
c      3
dtype: object

In [149]:
pd.Series(data = {'a': 1, 'b': 2.0, 'c': '3'})

a      1
b    2.0
c      3
dtype: object

In [151]:
sr[sr == 3]

c    3.0
dtype: float64

In [153]:
sr

a    1.0
b    2.0
c    3.0
dtype: float64

In [152]:
sr[0]

C:\Users\user\AppData\Local\Temp\ipykernel_18984\3717362250.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sr[0]


np.float64(1.0)

In [154]:
sr.iloc[0]

np.float64(1.0)

In [155]:
sr['a']

np.float64(1.0)

In [156]:
sr.loc['a']

np.float64(1.0)

In [157]:
sr[0:3]

a    1.0
b    2.0
c    3.0
dtype: float64

In [158]:
sr['a':'c']

a    1.0
b    2.0
c    3.0
dtype: float64

In [159]:
sr0 = pd.Series(data = [1, 2, 3], index = ['c', 'a', 'b'])
sr0

c    1
a    2
b    3
dtype: int64

In [160]:
sr0['a':'c']

Series([], dtype: int64)

In [161]:
sr0['c':'a']

c    1
a    2
dtype: int64

In [162]:
sr0.loc['c':'a']

c    1
a    2
dtype: int64

In [163]:
sr0.iloc[0:2]

c    1
a    2
dtype: int64

In [164]:
sr

a    1.0
b    2.0
c    3.0
dtype: float64

In [165]:
sr[[0, 2]]

C:\Users\user\AppData\Local\Temp\ipykernel_18984\1530571964.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sr[[0, 2]]


a    1.0
c    3.0
dtype: float64

In [166]:
sr[['a', 'c']]

a    1.0
c    3.0
dtype: float64

In [167]:
sr[[False, False, True]]

c    3.0
dtype: float64

In [168]:
sr[sr >= 3]

c    3.0
dtype: float64

In [169]:
sr.iloc[0]

np.float64(1.0)

In [170]:
sr.iloc[0:3]

a    1.0
b    2.0
c    3.0
dtype: float64

In [171]:
sr.iloc[[0]]

a    1.0
dtype: float64

In [172]:
sr.iloc[[0, 2]]

a    1.0
c    3.0
dtype: float64

In [173]:
sr.iloc[sr < 3]

ValueError: iLocation based boolean indexing cannot use an indexable as a mask

In [174]:
sr

a    1.0
b    2.0
c    3.0
dtype: float64

In [175]:
sr.loc['a']

np.float64(1.0)

In [176]:
sr.loc['a':'c']

a    1.0
b    2.0
c    3.0
dtype: float64

In [177]:
sr.loc[['a']]

a    1.0
dtype: float64

In [178]:
sr.loc[['a', 'c']]

a    1.0
c    3.0
dtype: float64

In [179]:
sr.loc[sr < 3]

a    1.0
b    2.0
dtype: float64

In [180]:
sr1 = pd.Series(data = li1, index = range(1, 4))
sr1

1      1
2    2.0
3      3
dtype: object

In [181]:
sr1[0]

KeyError: 0

In [182]:
sr1.iloc[0]

1

In [184]:
sr1.loc[1]

1

In [185]:
sr2 = pd.Series(data = li1, index = [1]*3)
sr2

1      1
1    2.0
1      3
dtype: object

In [186]:
sr2.loc[1]

1      1
1    2.0
1      3
dtype: object

In [187]:
sr2.iloc[0]

1

In [188]:
sr

a    1.0
b    2.0
c    3.0
dtype: float64

In [189]:
sr.loc['d'] = 4
sr

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64

In [190]:
sr.loc['d'] = 5
sr

a    1.0
b    2.0
c    3.0
d    5.0
dtype: float64

In [191]:
sr.drop(index = 'd')

a    1.0
b    2.0
c    3.0
dtype: float64

In [193]:
sr >= 1

a    True
b    True
c    True
d    True
dtype: bool

In [194]:
(sr >= 1) & (sr < 3)

a     True
b     True
c    False
d    False
dtype: bool

In [195]:
(sr >= 1) | (sr < 3)

a    True
b    True
c    True
d    True
dtype: bool

In [196]:
(sr >= 1) ^ (sr < 3)

a    False
b    False
c     True
d     True
dtype: bool

In [197]:
~((sr >= 1) & (sr < 3))

a    False
b    False
c     True
d     True
dtype: bool

In [198]:
sr1

1      1
2    2.0
3      3
dtype: object

In [199]:
sr3 = sr1

In [202]:
id(sr1) == id(sr3)

True

In [203]:
sr3.iloc[0] = 2
sr3

1      2
2    2.0
3      3
dtype: object

In [204]:
sr1

1      2
2    2.0
3      3
dtype: object

In [205]:
sr4 = sr1.copy()

In [206]:
id(sr1) == id(sr4)

False

In [208]:
sr4.iloc[0] = 1
sr4

1      1
2    2.0
3      3
dtype: object

In [209]:
sr1

1      2
2    2.0
3      3
dtype: object

In [210]:
li2 = [[1, 2], [3, 4], [5.0, '6']]
li2

[[1, 2], [3, 4], [5.0, '6']]

In [211]:
np.array(object = li2)

array([['1', '2'],
       ['3', '4'],
       ['5.0', '6']], dtype='<U32')

In [212]:
df = pd.DataFrame(data = li2)
df

0  1
0  1.0  2
1  3.0  4
2  5.0  6

In [213]:
type(df)

pandas.core.frame.DataFrame

In [214]:
df.shape

(3, 2)

In [215]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [216]:
df.columns

RangeIndex(start=0, stop=2, step=1)

In [217]:
df.dtypes

0    float64
1     object
dtype: object

In [218]:
df.values

array([[1.0, 2],
       [3.0, 4],
       [5.0, '6']], dtype=object)

In [219]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       3 non-null      float64
 1   1       3 non-null      object 
dtypes: float64(1), object(1)
memory usage: 180.0+ bytes


In [220]:
df.index = range(1, 4)
df

0  1
1  1.0  2
2  3.0  4
3  5.0  6

In [221]:
df.columns = ['A', 'B']
df

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [222]:
pd.DataFrame(data = li2, index = range(1, 4), columns = ['A', 'B'])

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [223]:
df

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [224]:
df.iloc[0]

A    1.0
B      2
Name: 1, dtype: object

In [225]:
df.iloc[0:2]

A  B
1  1.0  2
2  3.0  4

In [226]:
df.iloc[[1, 0]]

A  B
2  3.0  4
1  1.0  2

In [227]:
df.iloc[[1, 0], :]

A  B
2  3.0  4
1  1.0  2

In [228]:
df.iloc[:, 0]

1    1.0
2    3.0
3    5.0
Name: A, dtype: float64

In [229]:
df.iloc[:, 0:2]

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [230]:
df.iloc[:, [1, 0]]

B    A
1  2  1.0
2  4  3.0
3  6  5.0

In [231]:
df

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [232]:
df.loc[1]

A    1.0
B      2
Name: 1, dtype: object

In [233]:
df.loc[1:2]

A  B
1  1.0  2
2  3.0  4

In [234]:
df.loc[[1, 3]]

A  B
1  1.0  2
3  5.0  6

In [235]:
df.loc[[1, 3], :]

A  B
1  1.0  2
3  5.0  6

In [237]:
df.loc[:, 'A']

1    1.0
2    3.0
3    5.0
Name: A, dtype: float64

In [238]:
df.loc[:, 'A':'B']

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [239]:
df.loc[:, ['B', 'A']]

B    A
1  2  1.0
2  4  3.0
3  6  5.0

In [240]:
df

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [241]:
df.loc[4] = [7.0, 8]
df

A    B
1  1.0    2
2  3.0    4
3  5.0    6
4  7.0  8.0

In [242]:
df['C'] = ['a', 'b', 'c', 'd']
df

A    B  C
1  1.0    2  a
2  3.0    4  b
3  5.0    6  c
4  7.0  8.0  d

In [243]:
df.loc[4, 'C'] = 'D'
df

A    B  C
1  1.0    2  a
2  3.0    4  b
3  5.0    6  c
4  7.0  8.0  D

In [244]:
df.drop(index = 4, columns = 'C')

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [245]:
import os
import numpy as np
import pandas as pd
import chardet

In [246]:
os.getcwd()

'C:\\Users\\user\\Documents\\project\\code'

In [247]:
os.chdir(path = 'C:\\Users\\user\\Documents\\project\\data')
os.getcwd()

'C:\\Users\\user\\Documents\\project\\data'

In [248]:
os.chdir(path = '..')
os.getcwd()

'C:\\Users\\user\\Documents\\project'

In [249]:
os.chdir(path = './code')
os.getcwd()

'C:\\Users\\user\\Documents\\project\\code'

In [250]:
os.chdir(path = '../data')
os.getcwd()

'C:\\Users\\user\\Documents\\project\\data'

In [251]:
os.chdir(path = r'C:\Users\user\Documents\project\data')
os.getcwd()

'C:\\Users\\user\\Documents\\project\\data'

In [253]:
os.mkdir(path = 'temp')

In [254]:
os.listdir()

['APT_Detail_Seoul_2024.csv',
 'APT_Detail_Seoul_2024.xlsx',
 'APT_Price_Seoul(2020~2024).xlsx',
 'APT_Price_Seoul_2020.csv',
 'APT_Price_Seoul_2021.csv',
 'APT_Price_Seoul_2022.csv',
 'APT_Price_Seoul_2023.csv',
 'APT_Price_Seoul_2024.csv',
 'KBO_Hitter_Stats_2024.csv',
 'KBO_Pitcher_Stats_2024.csv',
 'MPRC_2024.csv',
 'MPRC_2024.xlsx',
 'MPRC_List.xlsx',
 'MPRC_List_2.xlsx',
 'NA_Sample.xlsx',
 'temp',
 'test.png']

In [256]:
os.rmdir(path = 'temp')

In [257]:
files = os.listdir()
for file in files:
    if 'xlsx' in file:
        print(file)

APT_Detail_Seoul_2024.xlsx
APT_Price_Seoul(2020~2024).xlsx
MPRC_2024.xlsx
MPRC_List.xlsx
MPRC_List_2.xlsx
NA_Sample.xlsx


In [258]:
[file for file in files if 'xlsx' in file]

['APT_Detail_Seoul_2024.xlsx',
 'APT_Price_Seoul(2020~2024).xlsx',
 'MPRC_2024.xlsx',
 'MPRC_List.xlsx',
 'MPRC_List_2.xlsx',
 'NA_Sample.xlsx']

In [259]:
pd.read_excel('APT_Price_Seoul(2020~2024).xlsx')

Unnamed: 0                 데이터셋 소개 Unnamed: 2             Unnamed: 3  \
0             NaN  - 2020년 서울특별시 아파트 매매가격        NaN                    NaN   
1             NaN                     NaN        NaN                    NaN   
2             NaN                    거래금액       지역코드                    아파트   
3             NaN                 100,500      11680                삼익대청아파트   
4             NaN                 203,000      11680                   개포자이   
...           ...                     ...        ...                    ...   
83984         NaN                  54,800      11260                  현대휴앤미   
83985         NaN                  59,800      11260  한신아파트상가동유치원동(103~109)   
83986         NaN                  58,000      11260  한신아파트상가동유치원동(103~109)   
83987         NaN                  57,500      11260                한영(101)   
83988         NaN                  62,500      11260  한신아파트상가동유치원동(103~109)   

      Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  \
0            NaN        NaN        NaN        NaN        NaN        NaN   
1            NaN        NaN        NaN        NaN        NaN        NaN   
2            시도명        시군구        법정동         지번       건축년도          년   
3          서울특별시        강남구        개포동         12       1992       2020   
4          서울특별시        강남구        개포동       12-2       2004       2020   
...          ...        ...        ...        ...        ...        ...   
83984      서울특별시        중랑구        중화동         11       2007       2020   
83985      서울특별시        중랑구        중화동        450       1997       2020   
83986      서울특별시        중랑구        중화동        450       1997       2020   
83987      서울특별시        중랑구        중화동     274-51       2003       2020   
83988      서울특별시        중랑구        중화동        450       1997       2020   

      Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15  
0             NaN         NaN         NaN         NaN         NaN         NaN  
1             NaN         NaN         NaN         NaN         NaN         NaN  
2               월           일        등기일자         매도자        전용면적           층  
3               1          31         NaN         NaN       39.53          13  
4               1           6         NaN         NaN       134.3          17  
...           ...         ...         ...         ...         ...         ...  
83984          12           3         NaN         NaN      100.17           5  
83985          12           1         NaN         NaN       59.76          17  
83986          12           5         NaN         NaN       59.76          19  
83987          12           1         NaN         NaN      116.25           6  
83988          12          11         NaN         NaN       59.76          19  

[83989 rows x 16 columns]

In [260]:
%%time
dfs = pd.read_excel('APT_Price_Seoul(2020~2024).xlsx', 
                    sheet_name = None, 
                    usecols = range(1, 16), 
                    skiprows = 3, 
                    thousands = ',')

CPU times: total: 46.4 s
Wall time: 1min


In [261]:
type(dfs)

dict

In [263]:
dfs.keys()

dict_keys(['2020년', '2021년', '2022년', '2023년', '2024년'])

In [264]:
dfs['2020년']

거래금액   지역코드                    아파트    시도명  시군구  법정동      지번  건축년도  \
0      100500  11680                삼익대청아파트  서울특별시  강남구  개포동      12  1992   
1      203000  11680                   개포자이  서울특별시  강남구  개포동    12-2  2004   
2      180000  11680                개포주공6단지  서울특별시  강남구  개포동     185  1983   
3      285000  11680               디에이치아너힐즈  서울특별시  강남구  개포동    1281  2019   
4      171000  11680                개포주공7단지  서울특별시  강남구  개포동     185  1983   
...       ...    ...                    ...    ...  ...  ...     ...   ...   
83981   54800  11260                  현대휴앤미  서울특별시  중랑구  중화동      11  2007   
83982   59800  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동     450  1997   
83983   58000  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동     450  1997   
83984   57500  11260                한영(101)  서울특별시  중랑구  중화동  274-51  2003   
83985   62500  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동     450  1997   

          년   월   일  등기일자  매도자    전용면적   층  
0      2020   1  31   NaN  NaN   39.53  13  
1      2020   1   6   NaN  NaN  134.30  17  
2      2020   1  14   NaN  NaN   60.13  14  
3      2020   1   4   NaN  NaN   94.29  12  
4      2020   1  12   NaN  NaN   60.76   2  
...     ...  ..  ..   ...  ...     ...  ..  
83981  2020  12   3   NaN  NaN  100.17   5  
83982  2020  12   1   NaN  NaN   59.76  17  
83983  2020  12   5   NaN  NaN   59.76  19  
83984  2020  12   1   NaN  NaN  116.25   6  
83985  2020  12  11   NaN  NaN   59.76  19  

[83986 rows x 15 columns]

In [266]:
df1 = pd.concat(objs = dfs, ignore_index = True)
df1

C:\Users\user\AppData\Local\Temp\ipykernel_18984\3606030525.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df1 = pd.concat(objs = dfs, ignore_index = True)


거래금액   지역코드                    아파트    시도명  시군구  법정동     지번  건축년도  \
0       100500  11680                삼익대청아파트  서울특별시  강남구  개포동     12  1992   
1       203000  11680                   개포자이  서울특별시  강남구  개포동   12-2  2004   
2       180000  11680                개포주공6단지  서울특별시  강남구  개포동    185  1983   
3       285000  11680               디에이치아너힐즈  서울특별시  강남구  개포동   1281  2019   
4       171000  11680                개포주공7단지  서울특별시  강남구  개포동    185  1983   
...        ...    ...                    ...    ...  ...  ...    ...   ...   
231899   74000  11260  한신아파트상가동유치원동(102~102)  서울특별시  중랑구  중화동    450  1998   
231900   50500  11260              삼익아파트.상가동  서울특별시  중랑구  중화동    438  1995   
231901   60000  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동    450  1997   
231902   67000  11260  한신아파트상가동유치원동(102~102)  서울특별시  중랑구  중화동    450  1998   
231903   11000  11260                  범양프레체  서울특별시  중랑구  중화동  208-4  2012   

           년   월   일       등기일자  매도자    전용면적   층  
0       2020   1  31        NaT  NaN   39.53  13  
1       2020   1   6        NaT  NaN  134.30  17  
2       2020   1  14        NaT  NaN   60.13  14  
3       2020   1   4        NaT  NaN   94.29  12  
4       2020   1  12        NaT  NaN   60.76   2  
...      ...  ..  ..        ...  ...     ...  ..  
231899  2024  11  21 2024-12-13   개인   84.03  11  
231900  2024  11  13 2024-12-18   개인   59.34  10  
231901  2024  11  18 2024-11-20   개인   59.76   4  
231902  2024  11   2        NaT   개인   59.76   9  
231903  2024  12   7        NaT   개인   17.94  15  

[231904 rows x 15 columns]

In [268]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231904 entries, 0 to 231903
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype         
---  ------  --------------   -----         
 0   거래금액    231904 non-null  int64         
 1   지역코드    231904 non-null  int64         
 2   아파트     231904 non-null  object        
 3   시도명     231904 non-null  object        
 4   시군구     231904 non-null  object        
 5   법정동     231904 non-null  object        
 6   지번      231904 non-null  object        
 7   건축년도    231904 non-null  int64         
 8   년       231904 non-null  int64         
 9   월       231904 non-null  int64         
 10  일       231904 non-null  int64         
 11  등기일자    79535 non-null   datetime64[ns]
 12  매도자     56193 non-null   object        
 13  전용면적    231904 non-null  float64       
 14  층       231904 non-null  int64         
dtypes: datetime64[ns](1), float64(1), int64(7), object(6)
memory usage: 26.5+ MB


In [267]:
%time df1.to_excel('test.xlsx', index = False)

CPU times: total: 1min 50s
Wall time: 2min 24s


In [269]:
df1.head()

거래금액   지역코드       아파트    시도명  시군구  법정동    지번  건축년도     년  월   일 등기일자  \
0  100500  11680   삼익대청아파트  서울특별시  강남구  개포동    12  1992  2020  1  31  NaT   
1  203000  11680      개포자이  서울특별시  강남구  개포동  12-2  2004  2020  1   6  NaT   
2  180000  11680   개포주공6단지  서울특별시  강남구  개포동   185  1983  2020  1  14  NaT   
3  285000  11680  디에이치아너힐즈  서울특별시  강남구  개포동  1281  2019  2020  1   4  NaT   
4  171000  11680   개포주공7단지  서울특별시  강남구  개포동   185  1983  2020  1  12  NaT   

   매도자    전용면적   층  
0  NaN   39.53  13  
1  NaN  134.30  17  
2  NaN   60.13  14  
3  NaN   94.29  12  
4  NaN   60.76   2

In [270]:
df1.tail()

거래금액   지역코드                    아파트    시도명  시군구  법정동     지번  건축년도  \
231899  74000  11260  한신아파트상가동유치원동(102~102)  서울특별시  중랑구  중화동    450  1998   
231900  50500  11260              삼익아파트.상가동  서울특별시  중랑구  중화동    438  1995   
231901  60000  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동    450  1997   
231902  67000  11260  한신아파트상가동유치원동(102~102)  서울특별시  중랑구  중화동    450  1998   
231903  11000  11260                  범양프레체  서울특별시  중랑구  중화동  208-4  2012   

           년   월   일       등기일자 매도자   전용면적   층  
231899  2024  11  21 2024-12-13  개인  84.03  11  
231900  2024  11  13 2024-12-18  개인  59.34  10  
231901  2024  11  18 2024-11-20  개인  59.76   4  
231902  2024  11   2        NaT  개인  59.76   9  
231903  2024  12   7        NaT  개인  17.94  15

In [271]:
df1.sample(n = 5, random_state = 1234)

거래금액   지역코드        아파트    시도명  시군구    법정동    지번  건축년도     년   월   일  \
163874   59800  11290     삼부컨비니언  서울특별시  성북구    길음동  1276  1998  2023   9  20   
220404  105000  11710       한강극동  서울특별시  송파구    풍납동   508  1995  2024   6  22   
219634  313000  11710     레이크팰리스  서울특별시  송파구    잠실동    44  2006  2024   7   9   
56702   144000  11200   현대I-PARK  서울특별시  성동구  성수동2가   834  2003  2020  10   6   
181564   96000  11740  고덕리엔파크3단지  서울특별시  강동구    상일동   490  2011  2024   9  28   

             등기일자  매도자    전용면적   층  
163874 2023-12-15  NaN   59.94  14  
220404 2024-07-25   개인   84.76  13  
219634 2024-09-05   개인  135.82  28  
56702         NaT  NaN  116.22  11  
181564 2024-12-16   개인   84.83   5

In [274]:
files = os.listdir()
files = [file for file in files if 'Price' in file and 'csv' in file]
files

['APT_Price_Seoul_2020.csv',
 'APT_Price_Seoul_2021.csv',
 'APT_Price_Seoul_2022.csv',
 'APT_Price_Seoul_2023.csv',
 'APT_Price_Seoul_2024.csv']

In [276]:
pd.read_csv(files[0])

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 0: invalid start byte

In [279]:
with open(file = files[0], mode = 'rb') as file:
    text = file.read()

In [280]:
text[0:100]

b'\xb0\xc5\xb7\xa1\xb1\xdd\xbe\xd7,\xc1\xf6\xbf\xaa\xc4\xda\xb5\xe5,\xbe\xc6\xc6\xc4\xc6\xae,\xbd\xc3\xb5\xb5\xb8\xed,\xbd\xc3\xb1\xba\xb1\xb8,\xb9\xfd\xc1\xa4\xb5\xbf,\xc1\xf6\xb9\xf8,\xb0\xc7\xc3\xe0\xb3\xe2\xb5\xb5,\xb3\xe2,\xbf\xf9,\xc0\xcf,\xb5\xee\xb1\xe2\xc0\xcf\xc0\xda,\xb8\xc5\xb5\xb5\xc0\xda,\xc0\xfc\xbf\xeb\xb8\xe9\xc0\xfb,\xc3\xfe\n"10'

In [282]:
%time chardet.detect(text[0:100])

CPU times: total: 0 ns
Wall time: 996 μs


{'encoding': 'EUC-KR', 'confidence': 0.99, 'language': 'Korean'}

In [283]:
%time chardet.detect(text)

CPU times: total: 18.9 s
Wall time: 25.1 s


{'encoding': 'CP949', 'confidence': 0.99, 'language': 'Korean'}

In [286]:
%time pd.read_csv(files[0], encoding = 'CP949')

CPU times: total: 219 ms
Wall time: 305 ms


거래금액   지역코드                    아파트    시도명  시군구  법정동      지번  건축년도  \
0      100,500  11680                삼익대청아파트  서울특별시  강남구  개포동      12  1992   
1      203,000  11680                   개포자이  서울특별시  강남구  개포동    12-2  2004   
2      180,000  11680                개포주공6단지  서울특별시  강남구  개포동     185  1983   
3      285,000  11680               디에이치아너힐즈  서울특별시  강남구  개포동    1281  2019   
4      171,000  11680                개포주공7단지  서울특별시  강남구  개포동     185  1983   
...        ...    ...                    ...    ...  ...  ...     ...   ...   
83981   54,800  11260                  현대휴앤미  서울특별시  중랑구  중화동      11  2007   
83982   59,800  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동     450  1997   
83983   58,000  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동     450  1997   
83984   57,500  11260                한영(101)  서울특별시  중랑구  중화동  274-51  2003   
83985   62,500  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동     450  1997   

          년   월   일  등기일자  매도자    전용면적   층  
0      2020   1  31   NaN  NaN   39.53  13  
1      2020   1   6   NaN  NaN  134.30  17  
2      2020   1  14   NaN  NaN   60.13  14  
3      2020   1   4   NaN  NaN   94.29  12  
4      2020   1  12   NaN  NaN   60.76   2  
...     ...  ..  ..   ...  ...     ...  ..  
83981  2020  12   3   NaN  NaN  100.17   5  
83982  2020  12   1   NaN  NaN   59.76  17  
83983  2020  12   5   NaN  NaN   59.76  19  
83984  2020  12   1   NaN  NaN  116.25   6  
83985  2020  12  11   NaN  NaN   59.76  19  

[83986 rows x 15 columns]

In [291]:
%%time
df2 = pd.DataFrame()
for file in files:
    df = pd.read_csv(file, encoding = 'CP949', 
                     parse_dates = ['등기일자'], 
                     thousands = ',')
    df2 = pd.concat(objs = [df2, df], ignore_index = True)

CPU times: total: 875 ms
Wall time: 1.2 s


In [292]:
df2.tail()

거래금액   지역코드                    아파트    시도명  시군구  법정동     지번  건축년도  \
231899  74000  11260  한신아파트상가동유치원동(102~102)  서울특별시  중랑구  중화동    450  1998   
231900  50500  11260              삼익아파트.상가동  서울특별시  중랑구  중화동    438  1995   
231901  60000  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동    450  1997   
231902  67000  11260  한신아파트상가동유치원동(102~102)  서울특별시  중랑구  중화동    450  1998   
231903  11000  11260                  범양프레체  서울특별시  중랑구  중화동  208-4  2012   

           년   월   일       등기일자 매도자   전용면적   층  
231899  2024  11  21 2024-12-13  개인  84.03  11  
231900  2024  11  13 2024-12-18  개인  59.34  10  
231901  2024  11  18 2024-11-20  개인  59.76   4  
231902  2024  11   2        NaT  개인  59.76   9  
231903  2024  12   7        NaT  개인  17.94  15

In [293]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231904 entries, 0 to 231903
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype         
---  ------  --------------   -----         
 0   거래금액    231904 non-null  int64         
 1   지역코드    231904 non-null  int64         
 2   아파트     231904 non-null  object        
 3   시도명     231904 non-null  object        
 4   시군구     231904 non-null  object        
 5   법정동     231904 non-null  object        
 6   지번      231904 non-null  object        
 7   건축년도    231904 non-null  int64         
 8   년       231904 non-null  int64         
 9   월       231904 non-null  int64         
 10  일       231904 non-null  int64         
 11  등기일자    79535 non-null   datetime64[ns]
 12  매도자     56193 non-null   object        
 13  전용면적    231904 non-null  float64       
 14  층       231904 non-null  int64         
dtypes: datetime64[ns](1), float64(1), int64(7), object(6)
memory usage: 26.5+ MB


In [294]:
%time df2.to_csv('test.csv', index = False)

CPU times: total: 1.47 s
Wall time: 2.05 s


In [295]:
with open(file = 'test.csv', mode = 'rb') as file:
    text = file.read()

In [297]:
chardet.detect(text[0:100])

{'encoding': 'utf-8', 'confidence': 0.99, 'language': ''}

In [300]:
%time df3 = pd.read_csv('test.csv', low_memory = False)
df3.info()

CPU times: total: 547 ms
Wall time: 874 ms
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231904 entries, 0 to 231903
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   거래금액    231904 non-null  int64  
 1   지역코드    231904 non-null  int64  
 2   아파트     231904 non-null  object 
 3   시도명     231904 non-null  object 
 4   시군구     231904 non-null  object 
 5   법정동     231904 non-null  object 
 6   지번      231904 non-null  object 
 7   건축년도    231904 non-null  int64  
 8   년       231904 non-null  int64  
 9   월       231904 non-null  int64  
 10  일       231904 non-null  int64  
 11  등기일자    79535 non-null   object 
 12  매도자     56193 non-null   object 
 13  전용면적    231904 non-null  float64
 14  층       231904 non-null  int64  
dtypes: float64(1), int64(7), object(7)
memory usage: 26.5+ MB


In [301]:
%time df2.to_pickle('test.pkl')

CPU times: total: 15.6 ms
Wall time: 94.8 ms


In [302]:
%time df4 = pd.read_pickle('test.pkl')
df4.info()

CPU times: total: 78.1 ms
Wall time: 134 ms
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231904 entries, 0 to 231903
Data columns (total 15 columns):
 #   Column  Non-Null Count   Dtype         
---  ------  --------------   -----         
 0   거래금액    231904 non-null  int64         
 1   지역코드    231904 non-null  int64         
 2   아파트     231904 non-null  object        
 3   시도명     231904 non-null  object        
 4   시군구     231904 non-null  object        
 5   법정동     231904 non-null  object        
 6   지번      231904 non-null  object        
 7   건축년도    231904 non-null  int64         
 8   년       231904 non-null  int64         
 9   월       231904 non-null  int64         
 10  일       231904 non-null  int64         
 11  등기일자    79535 non-null   datetime64[ns]
 12  매도자     56193 non-null   object        
 13  전용면적    231904 non-null  float64       
 14  층       231904 non-null  int64         
dtypes: datetime64[ns](1), float64(1), int64(7), object(6)
memory usage: 26.5+ M

In [303]:
os.rename(src = 'test.pkl', dst = 'APT_List.pkl')

In [304]:
pd.to_pickle(obj = [df1, df2, df3], filepath_or_buffer = 'testAll.pkl')

In [305]:
pd.read_pickle(filepath_or_buffer = 'testAll.pkl')

[          거래금액   지역코드                    아파트    시도명  시군구  법정동     지번  건축년도  \
 0       100500  11680                삼익대청아파트  서울특별시  강남구  개포동     12  1992   
 1       203000  11680                   개포자이  서울특별시  강남구  개포동   12-2  2004   
 2       180000  11680                개포주공6단지  서울특별시  강남구  개포동    185  1983   
 3       285000  11680               디에이치아너힐즈  서울특별시  강남구  개포동   1281  2019   
 4       171000  11680                개포주공7단지  서울특별시  강남구  개포동    185  1983   
 ...        ...    ...                    ...    ...  ...  ...    ...   ...   
 231899   74000  11260  한신아파트상가동유치원동(102~102)  서울특별시  중랑구  중화동    450  1998   
 231900   50500  11260              삼익아파트.상가동  서울특별시  중랑구  중화동    438  1995   
 231901   60000  11260  한신아파트상가동유치원동(103~109)  서울특별시  중랑구  중화동    450  1997   
 231902   67000  11260  한신아파트상가동유치원동(102~102)  서울특별시  중랑구  중화동    450  1998   
 231903   11000  11260                  범양프레체  서울특별시  중랑구  중화동  208-4  2012   
 
            년   월   일       등기일자  매도자    전용면적   층 

In [306]:
a = 1
b = 2.0
c = '3'

In [307]:
pd.to_pickle(obj = [a, b, c], filepath_or_buffer='testAll2.pkl')

In [309]:
d, e, f = pd.read_pickle(filepath_or_buffer='testAll2.pkl')

In [310]:
print(d)
print(e)
print(f)

1
2.0
3


In [312]:
files = os.listdir()
files = [file for file in files if 'test' in file]

In [313]:
for file in files:
    os.remove(file)

In [314]:
os.listdir()

['APT_Detail_Seoul_2024.csv',
 'APT_Detail_Seoul_2024.xlsx',
 'APT_List.pkl',
 'APT_Price_Seoul(2020~2024).xlsx',
 'APT_Price_Seoul_2020.csv',
 'APT_Price_Seoul_2021.csv',
 'APT_Price_Seoul_2022.csv',
 'APT_Price_Seoul_2023.csv',
 'APT_Price_Seoul_2024.csv',
 'KBO_Hitter_Stats_2024.csv',
 'KBO_Pitcher_Stats_2024.csv',
 'MPRC_2024.csv',
 'MPRC_2024.xlsx',
 'MPRC_List.xlsx',
 'MPRC_List_2.xlsx',
 'NA_Sample.xlsx']